server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/wpz-benpao/springcloud-config.git
          search-paths:
            - springcloud-config
          force-pull: true
          username: wpz-benpao
          password: wpz331604
      label: main

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka/,http://localhost:7002/eureka/,

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'