server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      #开启从注册中心动态创建路由的功能，利用为服务名进行路由，其实就是负载均衡
      discovery:
        locator:
          enabled: true
      #=============具体路由列表========================================
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
            #- After=2020-11-28T16:58:40+08:00[Asia/Shanghai] #在这个时间后才生效
            #- Before=2021-11-28T16:58:40+08:00[Asia/Shanghai] #在这个时间前才有效
            ##在这个区间内有效
            #- Between=2020-11-28T16:58:40+08:00[Asia/Shanghai],2021-11-28T16:58:40+08:00[Asia/Shanghai]
            #- Cookie=username,wpz   # http://localhost:9527/payment/get/31 --cookie "username=wpz"
            #- Header=X-Request-Id,\d+  # 例如：http://localhost:9527/payment/get/31 --header "X-Request-Id:123"
            # - Host=**.pancras.com  # 例如：http://localhost:9527/payment/get/31 --host "www.pancras.com"
            #- Method=Get
            #带查询条件的，要有参数名username并且值为正整数才能路由
            #- Query=username,\d+  # 例如： http://localhost:9527/payment/get/31?username=132

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
# 对应在GateWayConfig配置类中
#        - id: gateway_route
#          uri: http://news.baidu.com/guoji
#          predicates:
#            - Path=/guoji

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7001.com:7001/eureka/